# Generated by Django 3.1.6 on 2021-02-13 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Image', models.ImageField(upload_to='uploads/')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Discount_Price', models.IntegerField()),
                ('Quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('In_Stock', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], default=True, max_length=20)),
            ],
        ),
    ]
