# Generated by Django 2.0.13 on 2021-02-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopwebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='In_Stock',
            field=models.CharField(choices=[('True', 'IN STOCK'), ('False', 'OUT OF STOCK')], default=True, max_length=20),
        ),
    ]
