# Generated by Django 2.0.13 on 2021-02-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopwebapp', '0004_auto_20210214_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_name',
        ),
    ]
