# Generated by Django 2.0.13 on 2021-02-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopwebapp', '0005_auto_20210214_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_name',
            new_name='category_id',
        ),
    ]
