# Generated by Django 2.0.13 on 2021-02-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopwebapp', '0008_product_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='writer',
        ),
    ]
