# Generated by Django 2.0.13 on 2021-02-13 23:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shopwebapp', '0009_remove_product_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_created_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 13, 23, 52, 30, 372189, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopwebapp.Category'),
        ),
    ]
