# Generated by Django 2.0.13 on 2021-02-13 23:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shopwebapp', '0010_auto_20210214_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_created_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 13, 23, 57, 48, 208571, tzinfo=utc)),
        ),
    ]
