# Generated by Django 2.0.13 on 2021-02-13 23:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shopwebapp', '0011_auto_20210214_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 13, 23, 58, 0, 809687, tzinfo=utc)),
        ),
    ]
