# Generated by Django 2.0.13 on 2021-02-14 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shopwebapp', '0012_auto_20210214_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_created_date',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2021, 2, 14, 7, 49, 14, 592919, tzinfo=utc)),
        ),
    ]
