# Generated by Django 2.0.13 on 2021-02-14 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shopwebapp', '0013_auto_20210214_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 14, 9, 57, 8, 994184, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_created_date',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2021, 2, 14, 9, 57, 8, 993108, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='In_Stock',
            field=models.CharField(choices=[(True, 'IN STOCK'), (False, 'OUT OF STOCK')], default=True, max_length=20),
        ),
    ]
