# Generated by Django 2.0.13 on 2021-02-14 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shopwebapp', '0015_auto_20210214_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 14, 13, 54, 53, 771080, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 14, 13, 54, 53, 771696, tzinfo=utc)),
        ),
    ]
