# Generated by Django 2.0.13 on 2021-02-14 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shopwebapp', '0017_auto_20210214_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 14, 14, 29, 38, 405154, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 14, 14, 29, 38, 405913, tzinfo=utc)),
        ),
    ]
